#!/usr/bin/env python3
"""
Program: split-antibody-antigen-files
File:    split-antibody-antigen-files.py

Version: V1.0
Date: 04.11.21
Function: Extract and process antigen and antibody chains from a PDB file 
          for input to docking algorithms.

Author: Oliver E. C. Hood

--------------------------------------------------------------------------

Description:
============
This program takes a PDB file containing the structure of an antibody (that
may or may not be bound by an antigen(s)) and returns the antibody and 
antigen(s) chains as separate PDB files. The antigen chain is processed 
(randomly rotated and transformed) before being written to the new PDB 
file.

--------------------------------------------------------------------------

Usage:
======
split-antibody-antigen-files PDBFILE

--------------------------------------------------------------------------

Revision History:
=================
V1.0   04.11.21   Original   By: OECH
"""

#*************************************************************************

# Import Libraries
import sys
from bioptools import (pdbgetchain, pdbtranslate, pdbrotate)
import random

#*************************************************************************

def getantigenchainid(PDBfile):
   """
   Read input file and extract the chain identifier for the antigen chain
   (if present)

   >>> getantigenchainid("test1.pdb")
   'None'
   >>> getantigenchainid("test2.pdb")
   'C'
   >>> getantigenchainid("test3.pdb")
   'Multiple chains'
   >>>

   """
   #Set antigen_count to zero
   antigen_count = 0
   #Open PDB file
   with open(PDBfile) as file:
      #Read rows in file
      rows = file.readlines()
      #Identify Antigen chains from PDB Header
      for line in rows:
         if 'CHAIN A' in line:
            #Increase antigen_count by 1
            antigen_count += 1
            #Split the line into individual words
            contents=line.split()
            #Extract the antigen chainid
            agchainid = contents[4]
         #Break loop when first ATOM coordinate is encountered
         if 'ATOM' in line:
            break
   #Return chainid for single antigen chain
   if antigen_count == 1:
      return agchainid
   elif antigen_count > 1:
      return 'Multiple chains'
   else:
      return 'No chains'

#*************************************************************************

def extractantigen_antibodychains(PDBfile):
   """
   Search input PDB file for number of antigen chains then extract the antigen and antibody chains if there is a single antigen chain

   >>> extractantigen_antibodychains("test1.pdb")
   'Multiple antigen chains'
   >>> extractantigen_antibodychains("test2.pdb")
   antigen_chain
   antibody_chains
   >>> extractantigen_antibodychains("test3.pdb")
   'No antigen'
   >>>

   """
   #Get the antigen's chain id
   agchainid = getantigenchainid(PDBfile)
   #Filter out files with multiple or no antigen chains
   if agchainid == 'Multiple chains':
      return 'Multiple antigen chains'
   elif agchainid == 'No chains':
      return 'No antigen'
   else:
      #Extract the antigen chain
      antigen_chain = pdbgetchain agchainid PDBfile
      #Extract the antibody chains
      antibody_chains = pdbgetchain H,L PDBfile
   return antigen_chain
   return antibody_chains



#*************************************************************************

def processantigenchain(antigen_chain):
   """
   Perform a random rotation and translation on the antigen chain generated by extractantigen_antibodychains()

   """

   #Randomly rotate the antigen
   rotatedfile = pdbrotate -x (random.randint(45,315)) -y (random.randint(45,315)) -z (random.randint(45,315)) antigen_chain
   #Randomly translate the antigen
   processed_antigen_chain = pdbtranslate -x (random.randint(-25,25)) -y (random.randint(-25,25)) -z (random.randint(-25,25)) rotatedfile
   #Return the processed antigen chain
   return processed_antigen_chain

#*************************************************************************

def writepdbfile(PDBfile, chain)
   """
   Write extracted antibody and (processed) antigen chains to a new pdb file

   """
   